### ISSUE TITLE
[Request] Add versioning to image for any changes

### ISSUE THREAD

**Issue by cavemandaveman** [NeoAssist/docker-keepalived#10]
We are preparing to use this in production, and it would be nice to have versioned images instead of just "latest".

Something like neoassist/docker-keepalived:1.0.0 or even timestamp versioning like 201610071051 would be fine.

**Comment by roynasser** [comment]
@cavemandaveman That sounds reasonable...  I havent had time to test the latest changes, can you confirm if it is working currently?  I can then make a tag to "fix" the current version, even if only as an RC... Thanks for the suggestion!

I have already updated docker hub settings to pull any tags and make them available as differnt versions, and the latest remains on the master branch.

**Comment by cavemandaveman** [comment]
After the last couple of PRs got merged in, everything looks to be stable to me!

**Comment by roynasser** [comment]
I'm going to close this as we now have a fixed tag which apparently is working (at least for cavemandaveman)...  Further changes will be made on the master and then pushed out as tags for either a stable or RC which should help prevent bugs from surfacing...

One issue I have noticed the docker image isnt fixed, instead its using references to latest and edge versions.  This can pose issues when the base image (alpine in this case) has its latest tag updated...
