### ISSUE TITLE
keepalived keeps restarting

### ISSUE THREAD

**Issue by clayrisser** [NeoAssist/docker-keepalived#13]
I can't figure out why, but keepalived keeps crashing and restarting. I went through and configured everything. I even have all of my ports open.

**Comment by roynasser** [comment]
That is weird... Can you give us a bit more information about what your system is, what version rancher you are using, etc?  AFAIK usage without rancher should be perfectly fine but hasnt been really tested as there are usually other ways of accomplishing the same needs which may be easier...

If you tell us a bit more about the environment and hosts you are running this on, as well as some logs, we can try and help.

take care!

**Comment by sjiveson** [comment]
No response so closing. Will reopen if @jamrizzi gets back.
