### ISSUE TITLE
VIP shared with more than two hosts possible?

### ISSUE THREAD

**Issue by pwFoo** [NeoAssist/docker-keepalived#22]
Is it possible to setup more than two containers to share a VIP between 3+ hosts?

**Comment by pwFoo** [comment]
It looks like it's possible?
```
io.rancher.scheduler.global: 'true'
```
global service will be deployed at each host in environment I think...

**Comment by sjiveson** [comment]
I've done it with four hosts without issues. That label does indeed ensure one container runs on each host in the Rancher environment in question.

**Comment by pwFoo** [comment]
Yes, thanks!
